import MainNavigationBar from "@/components/shared/navigationBar/MainNavigationBar";
import { Geist, Geist_Mono, Krub } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/footer/Footer";
import { AddressProvider } from "@/components/contextApi/context/AddressContext";
import { CartProvider } from "@/components/contextApi/context/CartContext";
import { WishlistProvider } from "@/components/contextApi/context/WishlistContext";


const krub = Krub({
  variable: "--font-krub",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "off carry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${krub.variable} antialiased mainContainer overflow-x-auto`}
      >
        <AddressProvider>
          <CartProvider>
            <WishlistProvider>
              <MainNavigationBar />
              {children}
              <Footer />
            </WishlistProvider>
          </CartProvider>
        </AddressProvider>
      </body>
    </html>
  );
}
